"""add runbooks recommendations and audit events

Revision ID: 0c3be326d50a
Revises: 11c7a64e011c
Create Date: 2026-09-04 23:12:47.356886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3be326d50a'
down_revision: Union[str, Sequence[str], None] = '11c7a64e011c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runbooks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('loaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name')
    )
    with op.batch_alter_table('runbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runbooks_number'), ['number'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('recommendation_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('runbook_sections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('runbook_id', sa.String(length=32), nullable=False),
    sa.Column('heading', sa.String(length=200), nullable=False),
    sa.Column('anchor', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['runbook_id'], ['runbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runbook_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runbook_sections_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_runbook_sections_runbook_id'), ['runbook_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('section_id', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.String(length=400), nullable=False),
    sa.Column('matched_codes', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('modified_steps', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['runbook_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'section_id', name='uq_recommendation_target')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_recommendations_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_status'), ['status'], unique=False)

    op.create_table('runbook_section_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['runbook_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runbook_section_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runbook_section_codes_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_runbook_section_codes_section_id'), ['section_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runbook_section_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runbook_section_codes_section_id'))
        batch_op.drop_index(batch_op.f('ix_runbook_section_codes_code'))

    op.drop_table('runbook_section_codes')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_status'))
        batch_op.drop_index(batch_op.f('ix_recommendations_section_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_number'))
        batch_op.drop_index(batch_op.f('ix_recommendations_incident_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('runbook_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runbook_sections_runbook_id'))
        batch_op.drop_index(batch_op.f('ix_runbook_sections_number'))

    op.drop_table('runbook_sections')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_number'))
        batch_op.drop_index(batch_op.f('ix_audit_events_incident_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('runbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runbooks_number'))

    op.drop_table('runbooks')
    # ### end Alembic commands ###
