"""add generated briefings

Revision ID: 5d4a34ce389c
Revises: 0c3be326d50a
Create Date: 2026-09-05 00:07:53.965025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4a34ce389c'
down_revision: Union[str, Sequence[str], None] = '0c3be326d50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('first_actions', sa.Text(), nullable=False),
    sa.Column('cited_section_ids', sa.String(length=400), nullable=False),
    sa.Column('gaps', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('briefings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_briefings_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_briefings_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_briefings_number'), ['number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('briefings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_briefings_number'))
        batch_op.drop_index(batch_op.f('ix_briefings_incident_id'))
        batch_op.drop_index(batch_op.f('ix_briefings_generated_at'))

    op.drop_table('briefings')
    # ### end Alembic commands ###
