"""triage reports replace briefings

Revision ID: 82fe9b70b96c
Revises: d7141110da7e
Create Date: 2026-09-07 21:51:25.054720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fe9b70b96c'
down_revision: Union[str, Sequence[str], None] = 'd7141110da7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('trace', sa.Text(), nullable=False),
    sa.Column('first_actions', sa.Text(), nullable=False),
    sa.Column('cited_section_ids', sa.String(length=400), nullable=False),
    sa.Column('gaps', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('triage_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_triage_reports_generated_at'), ['generated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_triage_reports_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_triage_reports_number'), ['number'], unique=True)

    with op.batch_alter_table('briefings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_briefings_generated_at'))
        batch_op.drop_index(batch_op.f('ix_briefings_incident_id'))
        batch_op.drop_index(batch_op.f('ix_briefings_number'))

    op.drop_table('briefings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefings',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.Column('incident_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('first_actions', sa.TEXT(), nullable=False),
    sa.Column('cited_section_ids', sa.VARCHAR(length=400), nullable=False),
    sa.Column('gaps', sa.TEXT(), nullable=True),
    sa.Column('model', sa.VARCHAR(length=64), nullable=False),
    sa.Column('generated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('briefings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_briefings_number'), ['number'], unique=1)
        batch_op.create_index(batch_op.f('ix_briefings_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_briefings_generated_at'), ['generated_at'], unique=False)

    with op.batch_alter_table('triage_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_triage_reports_number'))
        batch_op.drop_index(batch_op.f('ix_triage_reports_incident_id'))
        batch_op.drop_index(batch_op.f('ix_triage_reports_generated_at'))

    op.drop_table('triage_reports')
    # ### end Alembic commands ###
