"""add users and supervisor-gated sections

Revision ID: d7141110da7e
Revises: 5d4a34ce389c
Create Date: 2026-09-05 14:35:24.459519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7141110da7e'
down_revision: Union[str, Sequence[str], None] = '5d4a34ce389c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    with op.batch_alter_table('runbook_sections', schema=None) as batch_op:
        # server_default is required: rows already exist, and the database has
        # to be told what this column holds for them. Autogenerate cannot infer
        # it — a Python-side default only applies to objects this application
        # constructs, never to a backfill. False is the safe answer: an existing
        # section becomes supervisor-gated only when its runbook says so.
        batch_op.add_column(
            sa.Column(
                'requires_supervisor',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runbook_sections', schema=None) as batch_op:
        batch_op.drop_column('requires_supervisor')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    # ### end Alembic commands ###
